### ISSUE TITLE
Issue when training the frozen graph model 

### ISSUE THREAD

**Issue by gr8nishan** [mozilla/DeepSpeech#1337]
Hi , 
I am trying to train on top of the frozen graph model by using few audio files. Training is getting successful but i try to process the audio to get t ext it gives me below error. Any guidance will be helpful.

`2018-04-16 16:59:41.354495: E tensorflow/core/framework/op_segment.cc:53] Create                                                                                         kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shape                                                                                        s' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:f                                                                                        loat; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_                                                                                        size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_ar                                                                                        ray_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/                                                                                        TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_siz                                                                                        e=false, element_shape=[?,4096], identical_element_shapes=true, tensor_array_nam                                                                                        e="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica                                                                                        :0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slic                                                                                        e). (Check whether your GraphDef-interpreting binary is up to date with your Gra                                                                                        phDef-generating binary.).
2018-04-16 16:59:41.354604: E tensorflow/core/common_runtime/executor.cc:643] Ex                                                                                        ecutor failed to create kernel. Invalid argument: NodeDef mentions attr 'identic                                                                                        al_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:                                                                                        resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown                                                                                        >; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true                                                                                        ; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirect                                                                                        ional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FL                                                                                        OAT, dynamic_size=false, element_shape=[?,4096], identical_element_shapes=true,                                                                                         tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:l                                                                                        ocalhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnst                                                                                        ack/strided_slice). (Check whether your GraphDef-interpreting binary is up to da                                                                                        te with your GraphDef-generating binary.).
         [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_aft                                                                                        er_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,4096], identi                                                                                        cal_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/                                                                                        input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_                                                                                        rnn/bw/bw/TensorArrayUnstack/strided_slice)]]
Error running session: Invalid argument: NodeDef mentions attr 'identical_elemen                                                                                        t_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource,                                                                                         flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=d                                                                                        ynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=te                                                                                        nsor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn                                                                                        /bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dyna                                                                                        mic_size=false, element_shape=[?,4096], identical_element_shapes=true, tensor_ar                                                                                        ray_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/                                                                                        replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strid                                                                                        ed_slice). (Check whether your GraphDef-interpreting binary is up to date with y                                                                                        our GraphDef-generating binary.).
         [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_aft                                                                                        er_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,4096], identi                                                                                        cal_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/                                                                                        input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_                                                                                        rnn/bw/bw/TensorArrayUnstack/strided_slice)]]
`

This is my script to train the model.

python -u DeepSpeech.py \
  --train_files  /home/hdpuser/models/csv/TRAIN/TRAIN.csv \
  --dev_files  /home/hdpuser/models/csv/DEV/DEV.csv \
  --test_files /home/hdpuser/models/csv/TEST/TEST.csv \
  --train_batch_size 4 \
  --dev_batch_size 4 \
  --test_batch_size 4 \
  --n_hidden 2048 \
  --epoch 3 \
  --validation_step 1 \
  --early_stop True \
  --earlystop_nsteps 6 \
  --estop_mean_thresh 0.1 \
  --estop_std_thresh 0.1 \
  --dropout_rate 0.30 \
 --default_stddev 0.046875 \
  --learning_rate 0.0001 \
  --report_count 100 \
  --use_seq_length False \
  --export_dir /home/hdpuser/models/results/model_export/ \
  --checkpoint_dir /home/hdpuser/models/results/checkout/ \
  --decoder_library_path /home/hdpuser/DeepSpeech/NativeClient/native_client/libctc_decoder_with_kenlm.so  \
  --alphabet_config_path /home/hdpuser/models/alphabet.txt \
  --lm_binary_path  /home/hdpuser/models/lm.binary \
  --lm_trie_path  /home/hdpuser/models/trie \
  --initialize_from_frozen_model /home/hdpuser/models/output_graph.pb \

Thanks in advance

**Comment by lissyx** [comment]
@gr8nishan How do you process the audio ?

**Comment by lissyx** [comment]
It's likely you trained from master branch which relies on TensorFlow v1.6.0, and somehow the model is not compatible with the 0.1.1 binaries we published. You can grab new `native_client.tar.xz` and other Node/PIP packages from https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/cpu or https://tools.taskcluster.net/index/artifacts/project.deepspeech.deepspeech.native_client.master/gpu if you need CUDA for inference.

**Comment by gr8nishan** [comment]
Thanks a lot.. so just replacing the native client would work in converting the audio file to text or do i have to train again. Also i am using TensorFlow v1.5.0. Do what should be the next steps for me

**Comment by lissyx** [comment]
No need to train again. If you trained with v1.5.0, then it also makes sense you get that, and just using a newer client should be enough.

**Comment by gr8nishan** [comment]
I still get the same error just by replacing native client. I also tried upgrading the tensorflow version to 1.6.0 and trained again from the frozen model but that also gives the same error.

**Comment by lissyx** [comment]
@gr8nishan I insist, verify again, because that's the isssue you are facing.

**Comment by gr8nishan** [comment]
As of now it worked by using TF 1.4 will try it once again tomorrow with TF 1.6 and inform you.
