### ISSUE TITLE
issue with building v0.5.1

### ISSUE THREAD

**Issue by miguel-negrao** [mozilla/DeepSpeech#2208]
Hi

I'm having trouble building v0.5.1 libdeepspeech.so.

- Linux debian testing amd64 
- bazel: **Build label: 0.19.2**
- deepspeech repo: commit 4b29b78832036216b53f59b953639bde7cde7dfe (HEAD, tag: **v0.5.1**)
- tensorflow: commit 93dd14dce2e8751bcaab0a0eb363d55eb0cc5813 (HEAD -> for_deepspeech, **origin/r1.13**)

Directory structure

./deepspeech
./tensorflow
./tensorflow/nativeclient -> ../deepspeech/nativeclient (symlink)

In directory ./tensorflow:

After doing `./configure`

```
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
Starting local Bazel server and connecting to it...
ERROR: /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/native_client/BUILD:68:1: no such target '//tensorflow:rpi3':
 target 'rpi3' not declared in package 'tensorflow' defined by /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/tenso
rflow/BUILD and referenced by '//native_client:libdeepspeech.so'
ERROR: /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/native_client/BUILD:68:1: no such target '//tensorflow:rpi3-a
rmv8': target 'rpi3-armv8' not declared in package 'tensorflow' defined by /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/tensorflow/BUILD and referenced by '//native_client:libdeepspeech.so'
ERROR: Analysis of target '//native_client:libdeepspeech.so' failed; build aborted: Cannot compute config conditions
INFO: Elapsed time: 12.785s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 35 targets configured)
```

**Comment by miguel-negrao** [comment]
The issue is solved if I comment the offending lines:

```
        #"//tensorflow:rpi3": LINUX_LINKOPTS + ["-l:libstdc++.a"],
        #"//tensorflow:rpi3-armv8": LINUX_LINKOPTS + ["-l:libstdc++.a"],
```

In any case, it should be possible to compile the library without any changes to the config file...

**Comment by lissyx** [comment]
> tensorflow: commit 93dd14dce2e8751bcaab0a0eb363d55eb0cc5813 (HEAD -> for_deepspeech, **origin/r1.13**)

Is this from https://github.com/mozilla/tensorflow ? Because this commit does not match any of the `mozilla/tensorflow r1.13` ...

**Comment by miguel-negrao** [comment]
Ah, no, it was from the original tensorflow repo. Sorry, I swear I did read the readme. :-)

**Comment by lissyx** [comment]
> Ah, no, it was from the original tensorflow repo. Sorry, I swear I did read the readme. :-)

Is it that you missed reading at the proper place, or is there improvement that could be done to doc ?

**Comment by miguel-negrao** [comment]
> > Ah, no, it was from the original tensorflow repo. Sorry, I swear I did read the readme. :-)
> 
> Is it that you missed reading at the proper place, or is there improvement that could be done to doc ?

No improvements needed, I just didn't read carefully enough. :-)
