### ISSUE TITLE
Invalid argument: WAV data chunk 'QWDu' is too large

### ISSUE THREAD

**Issue by gqy2468** [mozilla/DeepSpeech#2271]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux ubuntu 4.4.0-116-generic
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream TensorFlow
- **TensorFlow version (use command below)**: 1.14.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: use CPU
- **GPU model and memory**: use CPU

When I was training my own model. I got this errror as follow: 

> Epoch 0 |   Training | Elapsed Time: 2:36:05 | Steps: 3016 | Loss: 221.455782                                                                                                                                                              2019-07-26 11:21:47.813410: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: WAV data chunk 'QWDu' is too large: 3667229085 bytes, but the limit is 2147483647

Is there anyone can tell me what's happened?

**Comment by dabinat** [comment]
By default, Wave files use 32-bit headers that limit them to 2 GB in size. Using a 64-bit header allows you to create much larger files.

It seems like DeepSpeech is expecting the file to have a 32-bit header and therefore be less than 2 GB. But that's a reasonable expectation since training usually occurs on lots of very short clips. What is the duration of your file?

**Comment by gqy2468** [comment]
The largest size of my wave files is only 436KB，it's bitrate is 256 kbps!
Strangely enough, this error was always happend when the elapsed time of my continuous training was about 2:36:00 and the steps was 3016 !!!

**Comment by lissyx** [comment]
@gqy2468 Well, is it possible your file is just corrupted ? Anyway, if TensorFlow chokes on it, there's not much that we can do, except if it's a bug and assist you filing it upstream.

**Comment by gqy2468** [comment]
My reference linking is https://discourse.mozilla.org/t/training-chinese-model/27769

**Comment by lissyx** [comment]
> My reference linking is https://discourse.mozilla.org/t/training-chinese-model/27769

? Can you elaborate ? That's not really helping ...

**Comment by gqy2468** [comment]
My training csv files were downloaded from http://blog.yuwu.me/wp-content/uploads/2018/07/thchs30-csv.tar.gz, and my training wave files were downloaded from http://www.openslr.org/resources/18/data_thchs30.tgz

**Comment by reuben** [comment]
You most likely have a corrupted file in or around batch 3016. I'd sort the file by wav_filesize, then multiply your training batch size by 3000, let's say the batch size is 10. Then I'd take files 3000*10 through 3010*10, and run them with batch size 1. Then you'll be able to find out exactly what the problematic file is.

**Comment by gqy2468** [comment]
I have checked all wave files and their size are all correct by using a shell script ! Now I have not any tools to check the file is not corrupted and I think the perhaps reason is my computer's memory is not enough ?!

**Comment by reuben** [comment]
I just gave you a tool to check if the file is not corrupted: https://github.com/mozilla/DeepSpeech/issues/2271#issuecomment-515354597

**Comment by dabinat** [comment]
@gqy2468 This script may help: https://github.com/dabinat/deepspeech-tools/blob/master/wav_check.py

Usage:
`python3 wav_check.py <directory to scan> >/dev/null`

**Comment by gqy2468** [comment]
Thanks! I will have a try today!

**Comment by gqy2468** [comment]
I didn't find any corrupted wave file by using my modified script: https://github.com/gqy2468/DeepSpeech/blob/master/bin/wav_check.py

Usage:
`python3 bin/wav_check.py data_thchs30/thchs30-train.csv`

**Comment by tsungruihon** [comment]
@gqy2468 i meet the same problem as yours. Have you solved it .?

**Comment by tsungruihon** [comment]
@gqy2468 May i ask can i communicate with you using `email` or `wechat` ?

**Comment by dabinat** [comment]
> I didn't find any corrupted wave files by using my modified script: https://github.com/gqy2468/DeepSpeech/blob/master/bin/wav_check.py
> 
> Usage:
> `python3 bin/wav_check.py data_thchs30/thchs30-train.csv`

Sounds like ffmpeg may be working around the error, in which case you could process every file in the directory with ffmpeg using the "-c:a copy" parameter, which will essentially rewrite the file structure to disk without re-encoding the media data. That should fix the error.

**Comment by tsungruihon** [comment]
@dabinat thank you dabinat. What you suggest solved the problem perfectly. Thank again.

```
#!/bin/bash

for name in *.wav;
do
    ffmpeg -i "$name" -c:a copy "tmp/$name"
done
```

**Comment by chungyeh** [comment]
Thanks @dabinat @tsungruihon.

I met same 'QWDu' error and ffmpeg -c:a copy resolved this issue. It can work normally now.

**Comment by tsungruihon** [comment]
@chungyeh  Glad to hear that.

**Comment by tsungruihon** [comment]
@chungyeh Now the training process goes well,  but i still get the blank result while in the test progress. Have you met that situation ?

**Comment by chungyeh** [comment]
I can run normally as below. It uses test file and output is not identical to test file transcription., est/D11_785.wav,315500,北 京 丰 台 区 农 民 自 己 花 钱 筹 办 万 佛 延 寿 寺  迎 春 庙 会 吸 引 了 区 内 六 十 支 秧 歌 队 参 赛.

./deepspeech --alphabet thchs30-alphabet.txt --lm thchs30-lm.binary --trie thchs30-trie  --model output_graph.pb --audio test/D11_785.wav
TensorFlow: v1.13.1-13-g174b4760eb
DeepSpeech: v0.5.1-0-g4b29b78
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2019-08-04 14:59:28.997947: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-04 14:59:29.071488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-04 14:59:29.072025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.55GiB
2019-08-04 14:59:29.072039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-08-04 14:59:29.329167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-04 14:59:29.329192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-08-04 14:59:29.329197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-08-04 14:59:29.329324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5324 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-08-04 14:59:29.340582: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-08-04 14:59:29.340608: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-08-04 14:59:29.340631: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-08-04 14:59:29.340637: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-08-04 14:59:29.522775: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
北 京 方 坛 区 农 民 自 主 化 学 朝 办 万 佛 延 寿 四 银 春 要 会 心 文 区 内 六 十 珍 张 的 队 参 赛

I followed steps in https://github.com/mozilla/DeepSpeech/issues/1977 to regenerate arpa, lm.binary and trie file due to trie error message during training.

**Comment by tsungruihon** [comment]
@chungyeh Now my testing result is below :

```
I FINISHED optimization in 1:24:20.813446
WARNING:tensorflow:From /data/zeng_ruihong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I Restored variables from best validation checkpoint at /data/zeng_ruihong/asr/DeepSpeech-0.5.1/result/thchs30_checkpoint/best_dev-13320, step 13320
Testing model on /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/thchs30-test.csv
Test epoch | Steps: 83 | Elapsed Time: 0:57:10
Test on /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/thchs30-test.csv - WER: 1.000000, CER: 1.000000, loss: 170.676422
--------------------------------------------------------------------------------
WER: 1.000000, CER: 1.288889, loss: 40.363464
 - src: "除 中 文 外 还 将 制 作 英 日 等 外 文 版 软 盘 以 方 便 海 外 用 户"
 - res: "这一安晋图务夫宗的文的外岸儿还将的之的作的一应用的日子转等的用务一个外要有文的儿白儿的儿啊牌它案儿夫一个塞方不边样的儿矮海儿外儿一用五户五不和"                                            
```

It seems that it doesn't have blank to split out the words. Do you have any suggestion .? May i contact you with `wechat` for convenient communication.

**Comment by tsungruihon** [comment]
@chungyeh Here's my inference on `D11_785.wav`. Seems weird.

```
/data/zeng_ruihong/asr/DeepSpeech-0.5.1$ deepspeech --alphabet /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/thchs30_alphabet.txt --lm /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/lm.bin --trie /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/trie --model result/thchs30_model/output_graph.pb --audio /data/zeng_ruihong/asr/data/data_thchs30/data/D11_785.wav
Loading model from file result/thchs30_model/output_graph.pb
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2019-08-05 19:02:48.782524: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-05 19:02:49.017306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:04:00.0
totalMemory: 11.93GiB freeMemory: 11.81GiB
2019-08-05 19:02:49.017360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-08-05 19:06:03.987040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-05 19:06:03.987090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-08-05 19:06:03.987096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-08-05 19:06:04.005403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11438 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:04:00.0, compute capability: 5.2)
2019-08-05 19:06:04.041432: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-08-05 19:06:04.041484: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-08-05 19:06:04.041499: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-08-05 19:06:04.041852: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
Loaded model in 1.95e+02s.
Loading language model from files /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/lm.bin /data/zeng_ruihong/asr/data/data_thchs30/thchs30_csv/trie
Loaded language model in 0.0107s.
Running inference.
2019-08-05 19:06:04.484543: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
在安弟晋弟晋北一些京军用行方的在买来的区的农物尼银行的资自己一个划二十七姐全的一条朝的发外二样的夫患案样夫王安一言人十寿用的夫四色儿子十五以影及春的一样某不会委以捕苦及其需月的文的区在内爱的一六有
的十之的及江的不的对的是才不自在儿不在
Inference took 1555.125s for 9.858s audio file.
```

**Comment by chungyeh** [comment]
@tsungruihon FYR

Before I trained the model, I do fit checkout v0.5.1. Master version seems to have something wrong when I run training or inferences. I forgot the detail. During training thchs30, the list I got is about 40-50.

**Comment by tsungruihon** [comment]
@chungyeh thanks chungyeh. One thing I would like to ask is why my trie file is jut 9 bytes ?
I just typed python util/taskcluster.py --branch “v0.5.1” --target "." and then get the trie file using

native_client/generate_trie /data/peter/asr/data/data_thchs30/thchs30_csv/thchs30_alphabet.txt /data/peter/asr/data/data_thchs30/thchs30_csv/lm.bin /data/peter/asr/data/data_thchs30/thchs30_csv/trie. 
I noticed the README.md in https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md, should i also follow the instruction in https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md ?

**Comment by chungyeh** [comment]
@tsungruihon 9 bytes trie file is bad one. Please use thchs30 vocabulary file to regenerate thchs30-word.arpa (I used 3 gram), then lm.binary and then generate true. The trie file should be about 45KBytes.

**Comment by tsungruihon** [comment]
@chungyeh thanks chungyeh. My `lm.binary`' s size is `1.3M`. Would you mind telling me whether mine is the same as yours ?

**Comment by tsungruihon** [comment]
@chungyeh thanks chungyeh. Would you mind sharing the process that you generate `trie` file and share your `trie` file ?

**Comment by chungyeh** [comment]
I used DeepSpeech Dockerfile to build docker image and running in docker.  When build docker image with DeepSpeech Dockerfile, those utilities will be generated. Not sure if this causes difference.

/DeepSpeech/native_client/kenlm/build/bin/lmplz -o 3 --text thchs30-vocabulary.txt --arpa thchs30-words.arpa
/DeepSpeech/native_client/kenlm/build/bin/build_binary -T -s thchs30-words.arpa thchs30-lm.binary
/DeepSpeech/native_client/generate_trie thchs30-alphabet.txt thchs30-lm.binary thchs30-trie

ls -la
1261375 Aug  3 15:22 thchs30-lm.binary
46255 Aug  3 15:21 thchs30-trie
130500 Aug  3 15:21 thchs30-vocabulary.txt
4036589 Aug  3  2018 thchs30-words.arpa

**Comment by tsungruihon** [comment]
@chungyeh. thanks chungyeh.  I get the code from the release page. May i ask whether we could run deepspeech on GPU using docker image build from dockerfile? I am quite new to Docker.  I will be really appreciated if you are willing to share more tutorial of buildding deep speech docker image from docker file.

**Comment by tsungruihon** [comment]
@lissyx @chungyeh I try to build docker from Dockerfile using `docker build -t deepspeech:v0.5.1 .`.

Then the below error shown up.

```
/data/peter/asr/DeepSpeech-0.5.1$ docker build -t deepspeech:v0.5.1 .
Sending build context to Docker daemon  500.3MB
Step 1/70 : FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
 ---> bdc0497c2295
Step 2/70 : RUN apt-get update && apt-get install -y --no-install-recommends         build-essential         curl         wget         git         python3         python3-dev         python3-pip        python3-wheel         python3-numpy         libcurl3-dev          ca-certificates         gcc         sox         libsox-fmt-mp3         htop         nano         swig         cmake         libboost-all-dev         zlib1g-dev         libbz2-dev         liblzma-dev         locales         pkg-config         libsox-dev         openjdk-8-jdk         bash-completion         g++         unzip
 ---> Using cache
 ---> 38fcd00ba9ea
Step 3/70 : RUN ln -s -f /usr/bin/python3 /usr/bin/python
 ---> Using cache
 ---> 7bfdc9448bb3
Step 4/70 : RUN apt-get install -qq -y --allow-downgrades --allow-change-held-packages libnccl2=2.3.7-1+cuda10.0 libnccl-dev=2.3.7-1+cuda10.0
 ---> Running in a48c8600de06
E: Version '2.3.7-1+cuda10.0' for 'libnccl2' was not found
E: Version '2.3.7-1+cuda10.0' for 'libnccl-dev' was not found
The command '/bin/sh -c apt-get install -qq -y --allow-downgrades --allow-change-held-packages libnccl2=2.3.7-1+cuda10.0 libnccl-dev=2.3.7-1+cuda10.0' returned a non-zero code: 100
```

**Comment by peterhon123** [comment]
@chungyeh Would you mind share your email ? thanks a lot.

**Comment by peterhon123** [comment]
@lissyx @reuben @kdavis-mozilla  @chungyeh  I have succeed in install deepspeech from DeepSpeech Dockfile. But i still get the 9 bytes `trie` file. What i did is below 

```
/DeepSpeech/native_client/kenlm/build/bin/lmplz -o 3 --text thchs30_vocabulary.txt --arpa thchs30-words.arpa
/DeepSpeech/native_client/kenlm/build/bin/build_binary -T -s thchs30-words.arpa thchs30-lm.binary
/DeepSpeech/native_client/generate_trie thchs30_alphabet.txt thchs30-lm.binary thchs30-trie
```

And here's the file size.

```
-rwxrwxr-x  1 1005 1005  177947 Aug  5 08:26 thchs30-dev.csv
-rw-r--r--  1 root root 1261151 Aug  6 10:57 thchs30-lm.binary
-rwxrwxr-x  1 1005 1005  495749 Aug  5 08:26 thchs30-test.csv
-rwxrwxr-x  1 1005 1005 1990244 Aug  5 08:24 thchs30-train.csv
-rw-r--r--  1 root root       9 Aug  6 10:58 thchs30-trie
-rw-r--r--  1 root root 1599677 Aug  6 10:57 thchs30-words.arpa
-rwxrwxr-x  1 1005 1005   11532 Aug  5 08:11 thchs30_alphabet.txt
-rwxrwxr-x  1 1005 1005  130492 Aug  5 08:11 thchs30_vocabulary.txt
```

**Comment by peterhon123** [comment]
@chungyeh hello chungyeh. According to #2290 @reuben , the `trie` file size should be 9 bytes. 

> If you're using a character-level LM (every space separated word in thchs30_vocabulary.txt is one grapheme long --reuben

Then why could you generate 45K bytes `trie` file ? I am so curious. Please send me a message if you could see this reply. Thanks a lot.

**Comment by chungyeh** [comment]
I have no idea why it is not 9 bytes.

**Comment by peterhon123** [comment]
@chungyeh thanks for reply. Would you mind sharing your `thchs30-lm.binary`, `thchs30-trie`, `thchs30-vocabulary.txt` and `thchs30-words.arpa` with a `zip` file ?  Thanks a lot. :pray::pray:

**Comment by peterhon123** [comment]
@chungyeh  My email is petertsengruihon@gmail.com, hope you are willing to contact with me. Thanks a lot. 🙏🙏

**Comment by chungyeh** [comment]
i used http://blog.yuwu.me/wp-content/uploads/2018/07/thchs30-csv.tar.gz from https://blog.yuwu.me/?p=3989

and also refer to https://github.com/mozilla/DeepSpeech/issues/1756 and refer to https://github.com/ailurus1991/ds_files/

**Comment by peterhon123** [comment]
@chungyeh thanks chungyeh. It seems that the problem is `vocabulary.txt`. I noticed that in https://github.com/ailurus1991/ds_files/, the `thchs30-vocabulary.txt` starts wtih `AND`. 

<hr>
<img width="977" alt="Screen Shot 2019-08-07 at 12 13 21 PM" src="https://user-images.githubusercontent.com/11624203/62594376-0c161d00-b90d-11e9-9328-2ea049d48048.png">
<hr>

After i followed this format, i could succeed generated 45 kb trie files. And got the correct result. #2271 

```
-rwxrwxr-x 1 1005 1005  162766 Aug  6 14:36 thchs30-dev.csv
-rw-r--r-- 1 root root 1261235 Aug  7 03:31 thchs30-lm.binary
-rwxrwxr-x 1 1005 1005  453334 Aug  6 14:36 thchs30-test.csv
-rwxrwxr-x 1 1005 1005 1820244 Aug  6 12:22 thchs30-train.csv
-rw-r--r-- 1 root root   46223 Aug  7 03:32 thchs30-trie
-rw-r--r-- 1 root root 1600592 Aug  7 03:31 thchs30-words.arpa
-rwxrwxr-x 1 1005 1005   11532 Aug  5 08:11 thchs30_alphabet.txt
-rwxrwxr-x 1 1005 1005  130496 Aug  7 03:29 thchs30_vocabulary.txt
```

**Comment by peterhon123** [comment]
@chungyeh It seems that it took me about 926.603s inference time for 9s audio file. What about yours ?

**Comment by chungyeh** [comment]
it took couple minutes @@

**Comment by lissyx** [comment]
Closing as it seems there is no issue here. Please use Discourse for discussions.
